### ISSUE TITLE
new text to graph function

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#1]
Write a function for the annotatrix that will allow for input of new text, perform a naïve tokenisation algorithm (e.g., break on whitespace), and pull the tokens in as nodes in a new [untagged] dependency graph.

**Comment by jonorthwash** [comment]
At some point the graph will need to be translated into conllu or CG or one of the other formats?

**Comment by maryszmary** [comment]
New plain text is already being visualized. So, what is to be done here, I think, is to convert it to something like conllu, right?
@jonorthwash, @ftyers, I think, the best option is converting it to CoNLL-U, because CG is anyway converted to CoNLL-U by the system at some point. (And adding edges now works for CoNLL-U). So, I'm going to:
1) add a new "format": *plain text*. 
2) add a button "convert to CoNLL-U" and make a support for converting plain text to CoNLL-U.

**Comment by jonorthwash** [comment]
Yes, I think that sounds like a good plan.  Keep in mind that the "conversion" will do naïve tokenisation—this should be included in any documentation we make in the future (e.g., at the end of the summer).

**Comment by maryszmary** [comment]
So, now
1) There is a button "COnvert to CoNLL-U", which works fine for plane text, but doesn't work for any other formats yet.
2) When you start adding arcs in the graphical part with plain text, it automatically converts to CoNLL-U.
e.g. I have some plain text:
![image](https://user-images.githubusercontent.com/16348652/27508038-eba2e898-58e5-11e7-93b4-f86ee8346341.png)

then I draw an arc:
![image](https://user-images.githubusercontent.com/16348652/27508040-fe4d5924-58e5-11e7-874d-6c4aed379867.png)

**Comment by jonorthwash** [comment]
See discussion in #40 about details of implementation.

**Comment by maryszmary** [comment]
Ok, I see. But the discussion in #40 is about switching between CG and CoNLL-U.
It seems to me, that this issue (#1) is done now and can be closed?

**Comment by jonorthwash** [comment]
Yeah, I guess so.  But per #40, once tokenised it should be automatically stored in conllu format.
