### ISSUE TITLE
Add support for visualising enhanced dependencies

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#178]
@jnivre asks if there is any tool that can be used to visualise enhanced dependencies. How hard would it be to add to annotatrix ? Does @FrancessFractal's library support them ? If so, how should they be visualised ? Perhaps below the nodes instead of above and in a different colour ?

**Comment by FrancessFractal** [comment]
> Does @FrancessFractal's library support them ?

Nope. The scope of our task that summer was focused mostly on the (re)tokenization features for use primarily with freshly parsed sentences, so we weren't very concerned with most of the fields aside from id and form. We left all fields not directly related to that as strings for simplicity, in part because conllu v2 was going to be released soon but hadn't quite been formalized yet and we didn't want to put a lot of effort into features that weren't necessary only to have the format changes potentially conflict with our design choices shortly after writing it. We figured any further features would be reconsidered if/when the need arises.  I guess that time is now :)

I don't think adding support for enhanced dependencies would be too difficult, but it would probably break backwards compatibility a little bit. I'll look into it for you, and let you know what might need to change if we added that feature!

**Comment by ftyers** [comment]
Thanks for the response! :) 

On the Annotatrix side: Setting up the system to allow switching between basic/enhanced representations isn't too hard. I've just done a bit of string processing for now. 

Commit 1efef55 adds support for viewing enhanced dependencies (click on the "magic" or "tree" icon to the lower right hand side of the text box). It hasn't been tested properly, but the general behaviour is:

* If `VIEW_ENHANCED` is `true` then we skip creating the basic dependencies, and we instead process the enhanced dependencies (they should contain all the basic dependencies anyway).
* Viewing them is still pretty bad because of how the arc layout is currently working. 

Note for @maryszmary the `enhanced representation` is the part of CoNLL-U in the `DEPS` field (column 9). It allows for a list of heads + relations. e.g. 

```
1    They     they    PRON    PRP    Case=Nom|Number=Plur               2    nsubj    2:nsubj|4:nsubj _
2    buy      buy     VERB    VBP    Number=Plur|Person=3|Tense=Pres    0    root     0:root _ 
3    and      and     CONJ    CC     _                                  4    cc       4:cc _
4    sell     sell    VERB    VBP    Number=Plur|Person=3|Tense=Pres    2    conj     0:root|2:conj _
5    books    book    NOUN    NNS    Number=Plur                        2    obj      2:obj|4:obj _
6    .        .       PUNCT   .      _                                  2    punct    2:punct _
```

The first token (They) in the enhanced representation is the subject or both "buy" and "sell".

**Comment by jnivre** [comment]
Thanks, Fran! I will look at this tomorrow, but please note that the enhanced dependencies don’t always contain all the basic dependencies (ellipsis, relative clauses).

Joakim

On 08 Nov 2017, at 21:38, Francis Tyers <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the response! :)

On the Annotatrix side: Setting up the system to allow switching between basic/enhanced representations isn't too hard. I've just done a bit of string processing for now.

Commit 1efef55<https://github.com/jonorthwash/ud-annotatrix/commit/1efef5553cc9b0b4955d79e237ae4c72f2ab1f07> adds support for viewing enhanced dependencies (click on the "magic" or "tree" icon to the lower right hand side of the text box). It hasn't been tested properly, but the general behaviour is:

  *   If VIEW_ENHANCED is true then we skip creating the basic dependencies, and we instead process the enhanced dependencies (they should contain all the basic dependencies anyway).
  *   Viewing them is still pretty bad because of how the arc layout is currently working.

Note for @maryszmary<https://github.com/maryszmary> the enhanced representation is the part of CoNLL-U in the DEPS field (column 9). It allows for a list of heads + relations. e.g.

1    They     they    PRON    PRP    Case=Nom|Number=Plur               2    nsubj    2:nsubj|4:nsubj _
2    buy      buy     VERB    VBP    Number=Plur|Person=3|Tense=Pres    0    root     0:root _
3    and      and     CONJ    CC     _                                  4    cc       4:cc _
4    sell     sell    VERB    VBP    Number=Plur|Person=3|Tense=Pres    2    conj     0:root|2:conj _
5    books    book    NOUN    NNS    Number=Plur                        2    obj      2:obj|4:obj _
6    .        .       PUNCT   .      _                                  2    punct    2:punct _


The first token (They) in the enhanced representation is the subject or both "buy" and "sell".

**Comment by ftyers** [comment]
Ok, no problem, it's a draft (knocked up in a couple of hours). If you think it might be useful then we can hack at it a bit more :) --- we were going to leave supporting editting the enhanced dependencies until a bit later, but I think visualising them won't be enormously difficult.

To do a proper job we'd need to support the null nodes too.

**Basic:**
![captura de 2017-11-08 21-49-04](https://user-images.githubusercontent.com/449545/32573543-ab33ea3c-c4ce-11e7-8d0e-6a6286fc461e.png)

**Enhanced:**
![captura de 2017-11-08 21-48-49](https://user-images.githubusercontent.com/449545/32573550-b0a92f86-c4ce-11e7-9e10-cf5f47d1cce4.png)

**Comment by jonorthwash** [comment]
Perhaps retaining the arrows would help make that less confusing.  We can probably also detect overlapping nodes and add a vertical stagger in those cases, but I don't know what the algorithm would be for detecting those.

**Comment by jonorthwash** [comment]
I'll try to fix the overlapping issue later.  See #161.  In the meantime, add arrows?

**Comment by jonorthwash** [comment]
FYI, I fixed the button (the fa problems you were having, @ftyers) in https://github.com/jonorthwash/ud-annotatrix/commit/6726b24220edee75c40bb2b912fa43f265a3b87d.

**Comment by jnivre** [comment]
Thanks for your efforts, guys. I think horizontal staggering is equally (or even more) important. When incoming and outgoing arrows end in the same position horizontally, it is impossible to see which ones are incoming and which ones are outgoing.

**Comment by ftyers** [comment]
@jnivre I think that's described in #62, it's something we're working on, thanks for the suggestion! :)

**Comment by jnivre** [comment]
Hi,

I wanted to test the prototype for displaying enhanced dependencies available at Fran’s site (https://ftyers.github.io/ud-annotatrix/standalone/annotator.html). It worked fine when I loaded a small file (504 sentences), but when I tried to load the full Swedish training set (~5000 sentences), it doesn’t seem to work. (I have been waiting 5-10 minutes to see whether it just took a long time to load.) Have you tested it with large files previously?

Best,
Joakim

On 08 Nov 2017, at 21:38, Francis Tyers <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the response! :)

On the Annotatrix side: Setting up the system to allow switching between basic/enhanced representations isn't too hard. I've just done a bit of string processing for now.

Commit 1efef55<https://github.com/jonorthwash/ud-annotatrix/commit/1efef5553cc9b0b4955d79e237ae4c72f2ab1f07> adds support for viewing enhanced dependencies (click on the "magic" or "tree" icon to the lower right hand side of the text box). It hasn't been tested properly, but the general behaviour is:

  *   If VIEW_ENHANCED is true then we skip creating the basic dependencies, and we instead process the enhanced dependencies (they should contain all the basic dependencies anyway).
  *   Viewing them is still pretty bad because of how the arc layout is currently working.

Note for @maryszmary<https://github.com/maryszmary> the enhanced representation is the part of CoNLL-U in the DEPS field (column 9). It allows for a list of heads + relations. e.g.

1    They     they    PRON    PRP    Case=Nom|Number=Plur               2    nsubj    2:nsubj|4:nsubj _
2    buy      buy     VERB    VBP    Number=Plur|Person=3|Tense=Pres    0    root     0:root _
3    and      and     CONJ    CC     _                                  4    cc       4:cc _
4    sell     sell    VERB    VBP    Number=Plur|Person=3|Tense=Pres    2    conj     0:root|2:conj _
5    books    book    NOUN    NNS    Number=Plur                        2    obj      2:obj|4:obj _
6    .        .       PUNCT   .      _                                  2    punct    2:punct _


The first token (They) in the enhanced representation is the subject or both "buy" and "sell".

**Comment by ftyers** [comment]
@jnivre this is a known problem, we're using the browser/JavaScript's `localStorage` to store the data in the standalone mode, and large treebanks (E.g. > 10,000 tokens) don't play nicely. The exact size varies by browser, but it can be between 3--10M I think. 

We also have a "server" mode based on Flask, but it is not documented yet.  @maryszmary could you document how to use the server version to load the Swedish training data ?

**Comment by arademaker** [comment]
> We also have a "server" mode based on Flask, but it is not documented yet. @maryszmary could you document how to use the server version to load the Swedish training data?

That would be great !

**Comment by yaskevich** [comment]
The issues related to a subject "Support for enhanced dependencies" should be described in a way reflecting current state of app development.

**Comment by jonorthwash** [comment]
@yaskevich, could you document and research this?  Try to answer the following questions:

1. What is the current state of enhanced dependencies support in Annotatrix?
2. What would full support of enhanced dependencies in Annotatrix look like?
3. What would it take to get between Annotatrix's current support to full support?

**Comment by yaskevich** [comment]
It seems that currently Annotatrix does support enhanced dependencies.
At least, it renders tree mentioned above.

So, with enhanced deps enabled:
![deps-enh](https://user-images.githubusercontent.com/522902/60297775-a740cd80-9931-11e9-9582-6487e21408a1.png)

And when disabled:
![deps](https://user-images.githubusercontent.com/522902/60297812-bcb5f780-9931-11e9-80b7-967ecfc44d80.png)

UI allows to switch between them.

The difference between current support and full support I guess maybe more experienced users could tell, those who work with enhanced dependencies on a daily basis.

**Comment by ftyers** [comment]
They doesn't look right.

Why are they red? 

This is kind of basic functionality:
https://github.com/jonorthwash/ud-annotatrix/issues/178#issuecomment-342954852

But it would be cool if the enhanced deps were below.

**Comment by jonorthwash** [comment]
Yeah, red is supposed to mean something's wrong.  I like the bluish teal in the example Fran linked to.

**Comment by yaskevich** [comment]
I see, so enhanced dependencies are not supported yet.

**Comment by jonorthwash** [comment]
"yet" is kind of wrong.  There has been some preliminary support for parsing them and visualising them.  It may be that currently none of this code exists anymore, or that some of it is broken, or that some pieces are now missing.  E.g., I'm pretty sure notarrix parses enhanced dependencies.  And I think there's some support for visualising them that's still functional.

**Comment by jonorthwash** [comment]
There does appear to be basic functionality here:

_ | regular view | enhanced dependencies view
--- | --- | ---
regular view | ![Screenshot 2022-06-10 at 12-21-21 UD Annotatrix](https://user-images.githubusercontent.com/963849/173109311-d22cadcc-c011-4dae-b323-70f374fb2180.png) | ![Screenshot 2022-06-10 at 12-21-15 UD Annotatrix](https://user-images.githubusercontent.com/963849/173109352-bd48d42f-6f7e-4067-8d04-71556e46eb7a.png)
table view | ![Screenshot 2022-06-10 at 12-21-28 UD Annotatrix](https://user-images.githubusercontent.com/963849/173109408-cbcec0b3-e778-4f2a-8329-530e8ee05fa6.png) | ![Screenshot 2022-06-10 at 12-21-06 UD Annotatrix](https://user-images.githubusercontent.com/963849/173109463-5dcd88ef-ed3e-4512-b71d-d67217a21f27.png)


But I see a few issues:
* Turning off enhanced dependencies view hides the enhanced dependencies from the CoNLL-U view (but only in regular view—it's fine in table view).
* The enhanced dependencies default to black arcs (probably okay).
* Multiple root nodes are not supported (and the enhanced root node overrides the regular one?)

**Comment by ftyers** [comment]
- In focus should be **black**, out of focus should be **dotted**. So e.g. if you're in enhanced mode, the basic deps are dotted and if you're in basic mode the enhanced ones are dotted. 
- The button is confusing I agree, magic wand is not the best icon for that, I'm open to suggestions...

**Comment by nschneid** [comment]
A tree vs. a Christmas tree?

**Comment by jonorthwash** [comment]
I just turned this into four new issues related to enhanced dependencies.  The basic functionality is there and works; there's just some bugs and interface issues.  I'm closing this issue to keep things tidy.
