### ISSUE TITLE
Modals don't work in server mode.

### ISSUE THREAD

**Issue by gstark0** [jonorthwash/ud-annotatrix#250]
@jonorthwash That's the issue you were talking about, I checked it and it seems that this is not really a problem with exporting options, but with all modal windows in server mode. Help modal looks the same. I will take a look at this.
<img width="1280" alt="screen shot 2018-01-16 at 17 40 53" src="https://user-images.githubusercontent.com/25964807/35000370-90921c98-fae4-11e7-81dc-562656df2611.png">

**Comment by jonorthwash** [comment]
Oh my.  :)

**Comment by jonorthwash** [comment]
As @maryszmary points out, `server.py` is probably trying to server the whole site when `*.html` is requested.  This should be an easy fix.

**Comment by maryszmary** [comment]
A more accurate description in this case is: the server was returning `annotator.html` every time `annotatrix/LITERALLY_ANY_STRING` was requested, because it is parsing `LITERALLY_ANY_STRING` as a corpus uuid (needed for retrieving the corpus from server) in this position. It can be fixed by adding if conditions to `corpus_page` in `server.py` like this:
>     if treebank_id == 'help.html':
>        return send_from_directory('../standalone', 'help.html')
