### ISSUE TITLE
Convert from plain text to CoNLL-U doesn't work

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#272]
Splitted is null:

![peek 2018-03-03 12-45](https://user-images.githubusercontent.com/449545/36933890-f00dbb1c-1ee0-11e8-9bb5-59ab7a09babb.gif)

**Comment by ftyers** [comment]
It seems to be working fine in 126a40ecd58f52c1cf7ee6bda98bf678d51879c4

**Comment by vondersam** [comment]
I think this problem is due to that the function txtCorpus2Conllu's input is a string matching a regex which sometimes doesn't match (for example, if your sentence does not have a period, question mark or exclamation mark at the end). That's why the null error. I have changed this so it accepts any string, including break lines. Now it should work with any string of any size or type. Let me know if this is the desired behaviour. You can see the change here:

https://github.com/vondersam/ud-annotatrix/blob/84ebfa3144c9ae5aa8510f0486cd2b0adbd96591/standalone/lib/converters.js#L59

**Comment by keggsmurph21** [comment]
![example](https://user-images.githubusercontent.com/9888800/37926943-0ef3ddfa-310f-11e8-9460-b63f1a2c3bac.gif)

I have a similar problem with Firefox & Chrome.  Instead of `splitted = null` I get `cy.$ is not a function`.  I've attached a gif of the problem on Chrome.

**Comment by ftyers** [comment]
@keggsmurph21 looks like you didn't click on the CoNLL-U tab...

**Comment by keggsmurph21** [comment]
Clicking the tab does nothing at all

**Comment by jonorthwash** [comment]
@keggsmurph21,
> Clicking the tab does nothing at all

Yes, that's the bug.  Clicking on the CoNLL-U tab is supposed to convert it to CoNLL-U format and display that.  Check out the version Fran says where it works (126a40e) and try it there.

Also related to this: #144.

**Comment by keggsmurph21** [comment]
fixed in new version
