### ISSUE TITLE
Add support for deleting arcs visually

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#35]
Perhaps with ctrl + click or shift + click on the label ?

**Comment by jonorthwash** [comment]
Arcs should be selectable by keyboard or mouse, and when selected the delete key should be able to delete them.  What @ftyers suggests could perhaps be a shortcut for this behaviour.

**Comment by maryszmary** [comment]
Done. (What @jonorthwash has described. I'll add the shortcuts described by @ftyers later.)
So, now it's possible to select (multiple) arcs by click and remove them with `delete` key.
e.g., selecting:
![image](https://user-images.githubusercontent.com/16348652/27512433-061bec4e-5948-11e7-85a5-bc83836af65e.png)

and pressing `delete` key:
![image](https://user-images.githubusercontent.com/16348652/27512434-257dcab2-5948-11e7-9ec1-e6301e498020.png)

**Comment by maryszmary** [comment]
BTW, 
> with ctrl + click or shift + click on the label

It seems a little bit strange for me to mix keyboard and mouse at the same time. I'd rather do a purely keyboard combination as a shortcut. What do you think?

**Comment by jonorthwash** [comment]
The idea of this mouse+keyboard combination is that you can easily just go around trimming the tree.  The behaviour your implemented also combines keyboard and mouse input to accomplish the task, just not simultaneously.  Perhaps there should be a keyboard way to select the nodes (then +`delete` is entirely keyboard) and a mouse-only way to delete (then click + that is mouse-only)?

One shortcoming of the current implementation: you can't _unselect_ an arc.  This makes an unfortunate state of affairs if you e.g. click on the wrong node :-P  Could you add support for this?  Otherwise it's looking good!

**Comment by maryszmary** [comment]
> Perhaps there should be a keyboard way to select the nodes (then +delete is entirely keyboard) and a mouse-only way to delete (then click + that is mouse-only)?

Hm, yes, you are right. I should implement both keyboard-only and mouse-only ways.

> One shortcoming of the current implementation: you can't unselect an arc.

It turned out hard to implement, basically because of having to detect the right nodes (with POSs) to unselect. I guess, I still can do it, but it would be a long and ugly solution, and I'd better wait till I rewrite the visualisation. For now, I've added a way to unselect all the arcs altogether: `backspace`.

**Comment by jonorthwash** [comment]
Okay, I think this is done too for now.  We'll go back through and tweak these things later.
