### ISSUE TITLE
Download, export functions not working - local - neither dynamic nor static

### ISSUE THREAD

**Issue by fractaldragonflies** [jonorthwash/ud-annotatrix#396]
Installed yesterday with some  hiccups on node/npm install. Both server and static access available.

** Loaded local corpus fine. But cannot download corpus from app.  Nor can I export figures in png nor latex. Click button but no response and no indication of change in my system. Downloading corpus is showstopper for me.  Figures I can get from other apps once I have sound conllu file. **

Also 'npm run server' elicits "ConfigError: Please provide ANNOTATRIX_GH_CLIENT_SECRET"
And use of 'npm run dev server elicited "    - dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate"

In both cases I still have access, but wonder what the side effects are on the app.

**Comment by fractaldragonflies** [comment]
Reviewed issue with Kenneth S. Thanks Kenneth.

Discovered that with Firefox, the download DOES work and the file goes to the Downloads folder (at least in my configuration).  Likewise the export image functions work as well. This applies to both the dynamic (server version) and static version.

With safari on MacOS 10.15.3 the download and export buttons and menu items did not work. The save and most other actions functioned as well.

**Comment by kmurphy4** [comment]
Hey @fractaldragonflies , thanks for reaching out.  

> Discovered that with Firefox, the download DOES work and the file goes to the Downloads folder (at least in my configuration). Likewise the export image functions work as well. This applies to both the dynamic (server version) and static version.
> 
> With safari on MacOS 10.15.3 the download and export buttons and menu items did not work. The save and most other actions functioned as well.

If I understand you correctly, you're saying that you only have issues when using this on Safari?  That's not particularly surprising, since I haven't tested this on Safari at all :^).  I do have access to a MacOS computer, so I can poke around at it and see if I notice anything that might be breaking these buttons.

> Also 'npm run server' elicits "ConfigError: Please provide ANNOTATRIX_GH_CLIENT_SECRET"

This isn't a major issue, but this error happens when you run the server without providing a [github API token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).  Without this environment variable, you won't be able to use some of the Github-related functionality (I haven't worked on this recently, so I'm not sure exactly what falls under this umbrella).

Once you've generated an API token, you can either run the server via
```bash
$ export ANNOTATRIX_GH_CLIENT_SECRET=xxx
$ npm run server
```
or
```bash
$ ANNOTATRIX_GH_CLIENT_SECRET=xxx npm run server
```

> And use of 'npm run dev server elicited " - dyld: lazy symbol binding failed: Symbol not found: _FSEventStreamCreate"

This sounds like a MacOS-specific issue.  Can you do me a favor and paste the output of these commands:
```bash
$ sw_vers
$ node --version
$ npm --version
$ npm view fsevents version
```

Thanks!

**Comment by kmurphy4** [comment]
> With safari on MacOS 10.15.3 the download and export buttons and menu items did not work. The save and most other actions functioned as well.

After doing a bit more research, it looks like Safari's handling of `click` events is broken and requires some sort of polyfill.  I probably won't have the bandwidth to fix this sort of thing for the next week or so, so I would just recommend using a browser that this app was developed with (either Firefox or Chrome).  Sorry about that!

**Comment by fractaldragonflies** [comment]
Not a problem to work with Firefox. 

Wrt Safari,  this is not the first app where I have had problems with some (but not all) buttons not detecting the click.

I doubt the Safari just randomly breaks some buttons versus others (maybe with only certain javascript functions), so wonder if there is something different in the configuration of the download and export buttons versus the ones that work.  

Thanks for your help.




John Miller
millerje@me.com
