### ISSUE TITLE
Condense spacing of graph diaplays

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#51]
Currently graphs look something like this:
![2017-08-05-15 19 22_001](https://user-images.githubusercontent.com/963849/28998244-28319f6e-79f4-11e7-9055-f89835b80a18.png)

However, many of the nodes are spaced much further apart than they need to be (horizontally), and the links are also spaced further apart than they need to be (vertically).  With a little shoring up of these spaces, a much more condensed graph can be created.  See edited version below:
![2017-08-05-15 19 22_003](https://user-images.githubusercontent.com/963849/28998256-4ab6d75c-79f4-11e7-9d34-0f0a0f4a1b0c.png)

**Comment by ftyers** [comment]
@maryszmary this issue is the one for what we discussed on the TODO list with horizontal arc spacing.

**Comment by ftyers** [comment]
The problem is that the nodes are equal length, according to the length of the longest word in the sentence. See `formLayout()` in `visualiser.js`.

**Comment by ftyers** [comment]
This is actually a lot more involved than it appears. I have made a small improvement in 493acd2 but it makes things worse in some cases too (although no node overlapping, but they do butt up against each other).

So, going into details, the grid layout makes equally spaced cells as wide as the length of the longest node. Then nodes are laid out along this grid. But obviously, not all nodes are the same width. 

Fixing this means making a whole new layout, which means getting the cytoscape code, and installing a tonne of dependencies and then adding a new layout engine, which I've done, it's called `tree.js`. 

Here is some of the relevant code

```
    var widthCoefs = [];
    var widths = [];
    for( let i = 0; i < nodes.length; i++ ){
      widthCoefs.push(1.0);
    }

...

      for( let i = 0; i < nodes.length; i++ ){
        widthCoefs[i] = widths[i] / cellWidth; // cellWidth = width of the longest node
        if(widthCoefs[i] < 0.8) {
          widthCoefs[i] = 0.8;
        }
      }
...
        var newX = 0;
        for(let ii = 0; ii < col; ii++) {
          newX += widthCoefs[ii] * cellWidth;
        }
        // this is where we set the final position
        x = newX + (cellWidth * widthCoefs[col]) / 2 + bb.x1;
        //x = col * cellWidth + cellWidth / 2 + bb.x1;
        y = row * cellHeight + cellHeight / 2 + bb.y1;


```

So, instead of calculating the width based on a fixed length of the nodes, we calculate it based on the size of the previous nodes. I would be happy to try out different ways of selecting this number.

**Comment by jonorthwash** [comment]
We discussed an algorithm that should be something like this (python-like pseudocode):

```
def cellCenter(n):
    return sum(longest(nodewidths[0:n], poswidths[0:n]))
      + padding*2*n
      + nodewidths[n]/2
```

**Comment by ftyers** [comment]
Implemented in caf2ef8 .

I'm not touching this code again.

![captura de 2017-11-02 22-50-41](https://user-images.githubusercontent.com/449545/32352159-51b465fc-c020-11e7-81ef-1f143c714fa3.png)

![captura de 2017-11-02 22-50-53](https://user-images.githubusercontent.com/449545/32352161-51f35366-c020-11e7-8d6f-0b3a73b558dd.png)

**Comment by jonorthwash** [comment]
https://github.com/jonorthwash/ud-annotatrix/commit/ba37969969eeb46b9b4eff216f9bcf73fbb926c6 results in a much more vertically condensed graph, like the one below:
![2017-11-03-01 50 55_001](https://user-images.githubusercontent.com/963849/32361728-8a929362-c039-11e7-9c89-ff89f46457e5.png)

It's actually not a great algorithm, but it should usually result in vertically much more condensed graphs than the ones it produced before.

**Comment by jonorthwash** [comment]
Updated default in https://github.com/jonorthwash/ud-annotatrix/commit/1c0c79c0fcfdd00965e29fe2540c53dcf32d4251 results in slightly easier-to-read labels around subtokens:
![2017-11-03-01 54 30_001](https://user-images.githubusercontent.com/963849/32361785-13d761ac-c03a-11e7-92e7-62f74f289545.png)
