### ISSUE TITLE
scrolling issue

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#56]
When splitting tokens, the [buggy] positioning of the input textbox sometimes makes both the graph and the entire page scroll. Using the scroll wheel / trackpad scrolling to try to reposition the page can result in zoom in/out on the graph depending on the position of the cursor. Perhaps page scrolling should be disabled entirely?

**Comment by maryszmary** [comment]
(From #54)

**Comment by maryszmary** [comment]
Disabled user scrolling in f9c9129622cbbde00d5cabd897eaf673f4a419b4.
Should I make a button to enable scrolling?

**Comment by jonorthwash** [comment]
> Should I make a button to enable scrolling?

Yes.  But the default zoom factor seems to be too much, even for short sentences.  E.g., the following:

![2017-08-26-15 10 00_001](https://user-images.githubusercontent.com/963849/29744312-ac935298-8a70-11e7-8bb5-3d95b561bb11.png)

Could you make it so that it zooms to the width of the window by default?

**Comment by ftyers** [comment]
This issue was closed, but a number of related issues remain: #51 and #116 for example.
