### ISSUE TITLE
more convenient way of turning one token into two subtokens

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#87]
At the moment the way of turning one token into two tokens of the same subtoken (for example splitting off clitics) is a bit involved, see video:

http://ilazki.thinkgeek.co.uk/~spectre/token-to-subtokens.mp4

There should be an easier way to do this.

**Comment by maryszmary** [comment]
The problem here is: the labels (shown in the visual graph) of subtokens are at the moment not tokens, but lemmas of the subtokens, as in the example below:
![image](https://user-images.githubusercontent.com/16348652/30076295-10124492-9281-11e7-843b-109c9ff84178.png)

So, this is actually a way of adding lemmas to just created subtokens. If you think that it is token what should be shown as a label of subtoken, the subtoken's nodes won't be empty, but lemmas will only be editable in text mode.

**Comment by ftyers** [comment]
In that view it should show the (partial) surface forms. e.g. "wan" and "na" not "want" and "to". 

For now having lemmas only editable in text view is fine. The mandatory parts of CoNLL-U are id-surface-pos-head-deprel.

**Comment by rueter** [comment]
Hi,

my firefox says the file corrupt. So is firefox corrupt?

jack

**Comment by maryszmary** [comment]
@ftyers, done.

**Comment by jonorthwash** [comment]
Has this issue been addressed?

**Comment by ftyers** [comment]
It seems to have been, or at least I'm not sure what I had in mind when I filed the bug.
