### ISSUE TITLE
Extra spaces at the end of a tag line in CG causes weirdness

### ISSUE THREAD

**Issue by spectie** [jonorthwash/ud-annotatrix#89]
Try this:

```
"<This>"
	"this" prn dem mf sg
"<is>"
	"be" vbser pres p3 sg
"<a>"
	"a" det ind sg
"<test>"
	"test" n sg  
"<.>"
	"." sent
```

Where there are extra spaces after 'n sg'

**Comment by ftyers** [comment]
Fixed!

**Comment by maryszmary** [comment]
@ftyers, did you fix it by these lines in drawTree?

>  // remove extra spaces at the end of lines. #89
> content = content.replace(/ +\n/, '\n');
> $("#indata").val(content);

Do you remember, what exactly was happening? I can't reproduce any weirdness even if i comment them out. Also, drawTree is probably not the best place for them, because it's supposed only to change the graphical view, not the text. I think, this code can go to somewhere in validation.js.

**Comment by ftyers** [comment]
Hmm, I'm not sure. I'm not sure it should go in `validation.js` as technically that's not invalid, it's just weird and bad. I'd prefer it go in the format handling code for CG.
